package org.openhab.cli.runtime.command.config.shell;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.ArgumentCaptor;
import org.openhab.cli.runtime.Options;
import org.openhab.cli.runtime.command.config.shell.fish.FishCompletionCommand;
import org.openhab.cli.runtime.command.config.shell.fish.FishCompletions;
import org.openhab.cli.runtime.service.Console;
import picocli.CommandLine;

class FishCompletionCommandTest {
    @TempDir
    Path directory;

    @CommandLine.Command(name = "oh", mixinStandardHelpOptions = true)
    static class Root {}

    @CommandLine.Command(
            name = "availableActionsForThing",
            description = "Read a thing's actions.",
            mixinStandardHelpOptions = true)
    static class Leaf {
        @CommandLine.Mixin
        Options options;

        @CommandLine.Parameters(index = "0")
        String thingUid;
    }

    private CommandLine commandLine(Console console) {
        var root = new CommandLine(new Root());
        root.addSubcommand(
                "action",
                new CommandLine(CommandLine.Model.CommandSpec.create().name("action"))
                        .addSubcommand("availableActionsForThing", new Leaf()));
        root.addSubcommand("completion", new FishCompletionCommand(console));
        return root.setCaseInsensitiveEnumValuesAllowed(true);
    }

    @Test
    void printsScriptByDefaultAndForShow() {
        var console = mock(Console.class);
        var root = commandLine(console);
        assertEquals(0, root.execute("completion"));
        assertEquals(0, root.execute("completion", "SHOW"));
        var scripts = ArgumentCaptor.forClass(String.class);
        verify(console, times(2)).write(scripts.capture());
        assertEquals(scripts.getAllValues().getFirst(), scripts.getAllValues().getLast());
        assertTrue(scripts.getValue().startsWith("# Generated by oh"));
        verifyNoMoreInteractions(console);
    }

    @Test
    void resolvesUserCompletionDirectory() {
        var home = directory.resolve("home");
        var xdg = directory.resolve("xdg");
        var fallback = home.resolve(".config/fish/completions/oh.fish");
        assertEquals(
                xdg.resolve("fish/completions/oh.fish"),
                FishCompletionCommand.completionFile(xdg.toString(), home.toString()));
        assertEquals(fallback, FishCompletionCommand.completionFile(null, home.toString()));
        assertEquals(fallback, FishCompletionCommand.completionFile("", home.toString()));
        assertEquals(fallback, FishCompletionCommand.completionFile("relative", home.toString()));
    }

    @Test
    void createsDirectoriesAndReplacesAnExistingCompletionFile() throws IOException {
        var target = directory.resolve("fish/completions/oh.fish");
        FishCompletionCommand.writeCompletions(target, "# old\n");
        FishCompletionCommand.writeCompletions(target, "# new – completions\n");
        assertEquals("# new – completions\n", Files.readString(target));
        assertFalse(Files.readString(target).contains("\r"));
        var blocked = directory.resolve("blocked");
        Files.writeString(blocked, "file");
        assertThrows(
                IOException.class, () -> FishCompletionCommand.writeCompletions(blocked.resolve("oh.fish"), "script"));
    }

    @Test
    void fishCompletesCommandsOptionsAndEnumValuesInTheirContext() throws Exception {
        try {
            var version = new ProcessBuilder("fish", "--version").start();
            Assumptions.assumeTrue(version.waitFor() == 0, "Fish is unavailable");
        } catch (IOException e) {
            Assumptions.abort("Fish is unavailable");
        }
        var script = directory.resolve("oh.fish");
        Files.writeString(
                script,
                FishCompletions.generate(commandLine(mock(Console.class)).getCommandSpec()));
        assertEquals(Set.of("action", "completion"), complete(script, "oh "));
        assertEquals(Set.of("availableActionsForThing"), complete(script, "oh action "));
        assertEquals(Set.of("show", "install"), complete(script, "oh completion "));
        assertTrue(complete(script, "oh action availableActionsForThing --base").contains("--base-url"));
        assertTrue(complete(script, "oh action availableActionsForThing --no-").contains("--no-pretty-print"));
        assertTrue(complete(script, "oh action availableActionsForThing uid --base")
                .contains("--base-url"));
        assertTrue(complete(script, "oh action availableActionsForThing --base-url action ")
                .isEmpty());
        assertTrue(complete(script, "oh action availableActionsForThing -- ").isEmpty());
        assertTrue(complete(script, "oh completion SHOW ").isEmpty());
    }

    private Set<String> complete(Path script, String command) throws Exception {
        var output = directory.resolve("fish-output.txt");
        var process = new ProcessBuilder(
                        "fish",
                        "--no-config",
                        "-c",
                        "source $argv[1]; complete -C $argv[2]",
                        script.toString(),
                        command)
                .redirectErrorStream(true)
                .redirectOutput(output.toFile())
                .start();
        assertTrue(process.waitFor(15, TimeUnit.SECONDS), "Fish completion timed out");
        var text = Files.readString(output);
        assertEquals(0, process.exitValue(), text);
        return text.lines().map(line -> line.split("\t", 2)[0]).collect(Collectors.toSet());
    }
}
