package org.openhab.cli.runtime.command.config.shell.fish;

import java.io.File;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Collectors;
import picocli.CommandLine.Model.ArgSpec;
import picocli.CommandLine.Model.CommandSpec;
import picocli.CommandLine.Model.OptionSpec;

/** Generates Fish completions from the same command model used to parse CLI arguments. */
final class FishCompletions {
    private FishCompletions() {}

    static String generate(CommandSpec root) {
        var commands = new LinkedHashMap<String, CommandSpec>();
        collect("root", root, commands);
        var script = new StringBuilder("""
                # Generated by oh _config shell fish completion show.
                # Regenerate after upgrading oh to pick up new commands and options.
                complete -c oh -e
                complete -c oh -f

                function __oh_command_path
                    set -l words (commandline -opc)
                    set -e words[1]
                    set -l node root
                    set -l positional 0
                    set -l skip 0
                    for word in $words
                        if test $skip -eq 1
                            set skip 0
                            continue
                        end
                        if test "$word" = --
                            return 1
                        end
                        switch "$node"
                """);
        commands.forEach((path, command) -> {
            script.append("            case ").append(quote(path)).append("\n                switch \"$word\"\n");
            command.subcommands().forEach((name, child) -> script.append("                    case ")
                    .append(quote(name))
                    .append("\n                        set node ")
                    .append(quote(path + "/" + name))
                    .append("\n                        set positional 0\n"));
            options(command).forEach((name, option) -> {
                script.append("                    case ").append(quote(name)).append("\n");
                script.append(
                        option.arity().min() > 0
                                ? "                        set skip 1\n"
                                : "                        continue\n");
            });
            script.append("""
                                    case '*'
                                        if not string match -q -- '-*' "$word"
                                            set positional (math $positional + 1)
                                        end
                                end
                    """);
        });
        script.append("""
                        end
                    end
                    printf '%s\\n' "$node" "$positional"
                end

                function __oh_at
                    set -l state (__oh_command_path)
                    test "$state[1]" = "$argv[1]"; or return 1
                    if set -q argv[2]
                        test "$state[2]" = "$argv[2]"
                    end
                end

                """);
        commands.forEach((path, command) -> {
            String prefix = "complete -c oh -n " + quote("__oh_at " + quote(path));
            command.subcommands().forEach((name, child) -> {
                if (!child.getCommandSpec().usageMessage().hidden()) {
                    script.append(prefix)
                            .append(" -a ")
                            .append(quote(quote(name)))
                            .append(" -d ")
                            .append(quote(description(
                                    child.getCommandSpec().usageMessage().description())))
                            .append('\n');
                }
            });
            options(command).forEach((name, option) -> {
                if (option.hidden()) return;
                script.append(prefix);
                if (name.startsWith("--")) script.append(" -l ").append(quote(name.substring(2)));
                else if (name.startsWith("-"))
                    script.append(name.length() == 2 ? " -s " : " -o ").append(quote(name.substring(1)));
                else return;
                script.append(" -d ").append(quote(description(option.description())));
                if (option.arity().min() > 0) script.append(" -r");
                if (option.type() == Path.class
                        || option.type() == File.class
                        || name.equals("--properties-file")
                        || name.equals("-p")) {
                    script.append(" -F");
                }
                appendCandidates(script, option);
                script.append('\n');
            });
            command.positionalParameters().forEach(parameter -> {
                if (!parameter.hidden() && candidates(parameter) != null) {
                    script.append("complete -c oh -n ")
                            .append(quote("__oh_at " + quote(path) + " "
                                    + parameter.index().min()));
                    appendCandidates(script, parameter);
                    script.append(" -d ")
                            .append(quote(description(parameter.description())))
                            .append('\n');
                }
            });
        });
        return script.toString();
    }

    private static void collect(String path, CommandSpec command, Map<String, CommandSpec> commands) {
        commands.put(path, command);
        command.subcommands().forEach((name, child) -> collect(path + "/" + name, child.getCommandSpec(), commands));
    }

    private static Map<String, OptionSpec> options(CommandSpec command) {
        var options = new LinkedHashMap<>(command.optionsMap());
        options.putAll(command.negatedOptionsMap());
        return options;
    }

    private static void appendCandidates(StringBuilder script, ArgSpec argument) {
        var candidates = candidates(argument);
        if (candidates != null) {
            var values = new java.util.ArrayList<String>();
            candidates.forEach(value ->
                    values.add(quote(argument.type().isEnum() ? value.toLowerCase(java.util.Locale.ROOT) : value)));
            script.append(" -a ").append(quote(String.join(" ", values)));
        }
    }

    private static Iterable<String> candidates(ArgSpec argument) {
        if (argument.completionCandidates() != null) return argument.completionCandidates();
        if (argument.type().isEnum()) {
            return Arrays.stream(argument.type().getEnumConstants())
                    .map(value -> ((Enum<?>) value).name())
                    .toList();
        }
        return null;
    }

    private static String description(String[] lines) {
        return Arrays.stream(lines)
                .map(line -> line.replace("%n", " ").replaceAll("[\\r\\n\\t]+", " "))
                .collect(Collectors.joining(" "));
    }

    private static String quote(String value) {
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'";
    }
}
